name: C++ CI

on:
  push:
    branches: [ vtk9 ]

  pull_request:
    branches: [ vtk9 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install packages 
      run: sudo apt-get install -y vtk9 cmake libproj-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
    - name: configure
      run:  mkdir build && cd build && cmake -DBUILD_GUI=OFF -DUSE_VTK_DICOM=OFF -DTESTDICOM2MESH=ON -DTESTDICOM2MESHLIB=ON -DBUILD_GUI=ON ..
    - name: make d2m
      run: cd build && make
    - name: Run Test
      run: ./build/lib/runLibTests && ./build/dicom2mesh/runD2MTests
